bishop as:1.0
bishop ms:1.0
bishop ss:1.0
king ss:1.0
knight as:1.0
knight ms:1.0
knight ss:1.0
pawn as:1.0
pawn ms:1.0
pawn ss:1.0
queen as:1.0
queen ms:1.0
queen ss:1.0
rook as:1.0
rook ms:1.0
rook ss:1.0
tempo:8.0